dataset: LJSpeech
path:
  corpus_path: /change/me/path/to/data/LJSpeech-1.1
  lexicon_path: lexicon/librispeech-lexicon.txt
  preprocessed_path: ./preprocessed_data/LJSpeech
  raw_path: ./raw_data
preprocessing:
  audio:
    max_wav_value: 32768.0
    sampling_rate: 22050
  energy:
    feature: phoneme_level
    normalization: true
  mel:
    mel_fmax: 8000
    mel_fmin: 0
    n_mel_channels: 80
  pitch:
    feature: phoneme_level
    normalization: true
  speaker:
    embedding: none
    pretrained_path: none
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  text:
    language: eng
    spe_feature_dim: 36
    text_cleaners:
    - english_cleaners
    use_spe_features: false
  use_moh_reader: false
  val_size: 512
